### ISSUE TITLE
New Releases of WPInternals?

### ISSUE THREAD

**Issue by quiret** [ReneLergner/WPinternals#10]
Dear developers of WPinternals, mainly Gustave,

when will there be a new official release of WPInternals available? Rene Lergner has not been active for more than a year and your recent changes to the tool seem very interesting (looking at your Twitter feed you improved the unlocking speed).

Yours,
Martin

**Comment by gus33000** [comment]
Yes, available here: https://github.com/ReneLergner/WPinternals/releases/tag/2.9
