### ISSUE TITLE
crash when downloading the model

### ISSUE THREAD

**Issue by zhmushan** [ReneLergner/WPinternals#11]
OS:
- build: 19037.1
- version: 2004
- edition: Windows 10 Pro

Model:
- Producttype: RM-1118
- Productcode: 059X4Z0
- Operatorcode: 000-CN

**Comment by gus33000** [comment]
Can you please try the new version and see if the issue is resolved for you now?
https://github.com/ReneLergner/WPinternals/releases/tag/2.9
