### ISSUE TITLE
Link click crashes WPinternals 2.9.0 & 2.9.1

### ISSUE THREAD

**Issue by jetspiking** [ReneLergner/WPinternals#24]
**Problem Description:** 
Clicking on the following URL's crashed WPinternals on my devices:
1. "Buying me a beer"
2. "www.wpinternals.net"
3. "Windows Device Recovery Tool"
4. "google search" (for both listed drivers)
5. "download" (for ffu-file)
6. "known bug" 
7.  etc.  

**Reproducing this bug:**
Click on any of the listed example URL's (Getting Started Tab), which leads to a crash. 

**Device Specification:**
The bug was reproduced on:

| Device | OS | Architecture |
| :---: | :---: | :---: |
| Aspire 5520G | Windows 7 | x64 |
| I7-4790 system | Windows 10 | x64 |

**WPinternals Version**
The bug has been verified to be present on version 2.9.0 & 2.9.1.

**Suspected Cause**
Difference in handling URL's to prior versions.

**Image**
![WPI_WDRT_CRASH_WIN7](https://user-images.githubusercontent.com/43465192/129106979-c08de537-cf9c-489a-a2a8-b80b731d86f5.png)

I'd be happy to provide more information, thank you for your work!

**Comment by gus33000** [comment]
Thanks! Fixed as of 2.9.2.

**Comment by DMFotoYDiseno** [comment]
![image](https://github.com/ReneLergner/WPinternals/assets/75050250/da023f71-f053-4f0a-a448-3af181403023)
Hello, WPInternals is a great job, of course about Lumia 950XL is so old issue, and today I have problems, FUU file download stops suddently, and I've try Ir a lot of times and at different hours... Can you help me to get this file?
