### ISSUE TITLE
Bad GPT error (Lumia 640XL)

### ISSUE THREAD

**Issue by lebao3105** [ReneLergner/WPinternals#29]
Hi, I want to unlock the bootloader for Lumia 640XL. I downloaded the FFU file from Download page but I can't unlock the bootloader. WPI shows the Bad GPT error. Please help me. Sorry for my English.
If you can't understand what am I saying, here are my images:
![image](https://user-images.githubusercontent.com/77564176/134332603-879b52aa-13a0-454b-bb52-705ad4b0b952.png)
![image](https://user-images.githubusercontent.com/77564176/134332878-e9a333b4-9298-4a55-b595-d054ff374ee6.png)

**Comment by gus33000** [comment]
Hi are you still having issues with this? This is likely caused by a corrupt ffu file.

**Comment by lebao3105** [comment]
I downloaded the image from LumiaFirmware, and it works.
Thank you for the app!
