### ISSUE TITLE
Error "Sequence contains no matching element" while unlocking

### ISSUE THREAD

**Issue by haikuotiankong114514** [ReneLergner/WPinternals#31]
### Description

Hi, I'm using WPInternals 2.9.2 to unlock my Lumia 638 to deploy xap files. But the WPInternals returned a `Sequence contains no matching element` error message and didn't continue. All the firmwares like ede files and ffu files were all downloaded from lumiafirmware.com.
What's wrong? Or did I just do sth wrong?

### Steps To Reproduce

Just go to unlock the phone using downloaded firmwares:-(

### Expected behavior

I just want to unlock my Lumia. That's ok

### WPinternals Version

2.9.2

### Windows Version

win7 service pack 1

### Phone model

Lumia 638(RM-1010), Model 059W0P1

### Relevant Assets
[WPInternals.log](https://github.com/ReneLergner/WPinternals/files/7359466/WPInternals.log)

**Comment by haikuotiankong114514** [comment]
> Hi have you found time to upload the log file you said you would upload later? Thanks in advance!

Done:)
Sorry for uploading so late

**Comment by gus33000** [comment]
Please try using WPinternals 3.0 preview 3, if the issue persists, please file a new issue
