### ISSUE TITLE
Does WPInternals >=2.9.2 works with Lumia 535?

### ISSUE THREAD

**Issue by PiQuK** [ReneLergner/WPinternals#32]
Hello

The program WPInternals has list of supported Lumia's systems. Important for me is one (Bootloader spec A):
...........
8.10.14234.375
...........

And above in the program we have: List of models with Bootloader Spec B)
...........
Lumia 535
...........

I have Lumias 535 with 8.10.14234.375
So, what type of bootloader it has?

Anyway, I can't unlock in it bootloader part 2, it seems like loop up to 64  (65) restarts - failed write to pipe :((((

Please make new version that will fix it :)

Kind regards
Piotr

**Comment by Daniel224455** [comment]
Use this guide : https://github.com/sonic011gamer/Lumia535Utils

for some reason WPinternals is too shitty or smth that it doesnt work

**Comment by PiQuK** [comment]
Hello

**Sorry for late response :)**
Thank you for the guide. After changes I've got:
_Windows Phone Internals version 2.9.7805.33507
Copyright Heathcliff74 / wpinternals.net
Waiting for phone to connect...
Connected device: Lumia
Mode: Mass storage mode
Break endless loop.
Phone is unlocked!_

That seems to be OK?

But while deploying of xap file, I have Error - 0x81030118 :((((

What more I have to do?
