### ISSUE TITLE
lumia 1520

### ISSUE THREAD

**Issue by AkariRiku** [ReneLergner/WPinternals#39]
can't anyone give specific information about the additional .ffu file in some more specific way,
I tried to unlock the bootloader, but it still doesn't work, 
Donor FFU RM1085_1078.0017.10586.13053.13829.030012_retail_prod_signed.ffu not work ( The OS version of the selected FFU is not supported. Select a donor-FFU with a supported OS version.)

**Comment by AkariRiku** [comment]
t hac, fixed!
using this https://androidfilehost.com/?fid=2188818919693774622 
RM1085_1078.0053.10586.13169.12547.035242_retail_prod_signed.ffu

**Comment by joaozittoo** [comment]
> t hac, fixed! using this https://androidfilehost.com/?fid=2188818919693774622 RM1085_1078.0053.10586.13169.12547.035242_retail_prod_signed.ffu

Dude, u save my life! **Thanks**
