### ISSUE TITLE
Request: Support for OS version 10.0.15254.562

### ISSUE THREAD

**Issue by JamePeng** [ReneLergner/WPinternals#4]
Microsoft was push the new W10M system 10.0.15254.562 this month, but the WPinternals notice said that was not support this version.

**Comment by Aarklendoia** [comment]
The lastest version is now 10.0.15254.566 !

**Comment by AxelPanda** [comment]
unfortunately, the latest version is 10.0.15254.572 now...
is there any way to prevent windows from updating?

**Comment by trochdewei** [comment]
> is there any way to prevent windows from updating?

there must be registry key. I don't remember exactly which. You can edit registry using interop tools

**Comment by davepermen** [comment]
10.0.15254.575 now..

**Comment by Aarklendoia** [comment]
For information, the last version of WPInternals supports all updates of Windows (current and future). It's only a problem to enable the root access, not to unlock the bootloader.

**Comment by davepermen** [comment]
Root access is the one needed to extract the WhatsApp messages.db to move it over to Android, so I guess that's one reason there's interest specifically towards the root access.

**Comment by HimbeersaftLP** [comment]
Any updates?

**Comment by mandrearg** [comment]
I'm interested too in support for this Windows Mobile 10 build, I wasn't able to root access my Lumia 550 becasue this build isn't supported by WPInternals 2.8

**Comment by vluizflavio** [comment]
Also does not support Lumia 640XL, OS version 10.0.15063.1868

**Comment by gersteba** [comment]
Please support newest version 10.0.15254.597, too - thank you!

**Comment by quiret** [comment]
Please read my discussion with Csybormelgen at woaproject.net to fix problems due to outdated wpinternals (because it lacks support for latest W10M builds):

https://www.woaproject.net/viewtopic.php?f=17&t=85#p489

**Comment by MagicAndre1981** [comment]
The final build of Windows 10 mobile is 10.0.15254.600. 

any chance to get an up to date version @gus33000 @ReneLergner

**Comment by SIRprise** [comment]
I don't remember exactly what I did (and my phone is now bricked), but to get the WhatsApp database and other stuff I did not need the root access:
- unlocked the bootloader and backuped everything
- saved bin-files of the filesystems
- enabled mass storage mode with access to filesystem, changed permissions to access the whatsapp folder and copied it. 

I think the last step was not neccessary: With the .bin-file you can use the tool IsoBuster and browse through the filesystem.
A german version of what I did is here:
[https://www.wpvision.de/ich-brauche-hilfe-bei/11347-lumia-650-dateisystem-zugriff.html](url)

**Comment by gus33000** [comment]
Root Access isn't required to access files on the phone. You can do that using Mass Storage.

**Comment by hanlong85** [comment]
> I don't remember exactly what I did (and my phone is now bricked), but to get the WhatsApp database and other stuff I did not need the root access:
> 
> * unlocked the bootloader and backuped everything
> * saved bin-files of the filesystems
> * enabled mass storage mode with access to filesystem, changed permissions to access the whatsapp folder and copied it.
> 
> I think the last step was not neccessary: With the .bin-file you can use the tool IsoBuster and browse through the filesystem.
> A german version of what I did is here:
> [https://www.wpvision.de/ich-brauche-hilfe-bei/11347-lumia-650-dateisystem-zugriff.html](url)

where to find the bin-files?

**Comment by tkjune** [comment]
> I hate to be that guy, but on my phone I read version **10.0.15254.603**.
> As far as release notes tell me, I suppose version 2.8 of WPInternals is not compatible with this WP build, right?

Tested... 10.0.15254.603 not supported :(

**Comment by AMBNETO** [comment]
It maybe not 100% supported, but I managed to unlock my bootloader using WPInternals 2.8 (version 15254.603). It will not download the emergency files, you will need to download generic ones over the internet. But that it's, then you click on Unlock Bootloader and it will work. If the process fails, try again. I tried 4 times and it worked.

**Comment by gus33000** [comment]
Support for the latest build of Windows phone was added by a24998c #15 
I am closing this issue as a result, if you feel like support for older revisions need to be added, feel free to reply on this thread and I might reopen it.
