### ISSUE TITLE
Downloads Tab Crash

### ISSUE THREAD

**Issue by SleepyBoi2852** [ReneLergner/WPinternals#52]
### Description

When I try to open the downloads tab with a phone plugged in, it crashes. It does not happen without the phone

### Steps To Reproduce

1. Open WPInternals
2. Connect Nokia Lumia 520
3. Click "Downloads"
4. Crash

https://github.com/ReneLergner/WPinternals/assets/35126957/35544fb5-7b68-4abd-8c5b-7b6ec07ea1f8

### Expected behavior

It should go to the downloads page

### WPinternals Version

v2.9.2

### Windows Version

Windows 11 22H2 22621.1928

### Phone model

Lumia 520

### Relevant Assets

[WPInternals.log](https://github.com/ReneLergner/WPinternals/files/11924612/WPInternals.log)

**Comment by gus33000** [comment]
FFU download functionality is deprecated.
