### ISSUE TITLE
Issues regarding Label mode (the program closes unexpectedly on both cases).

### ISSUE THREAD

**Issue by NeoSDAP** [ReneLergner/WPinternals#60]
### Description

It is possible that this option is not commonly used, but when you want to use it, it does not work correctly, at least in my case.

1. When I want to switch to label mode, before flashing the SECWIM file to the device, the program quits unexpectedly because, according to the log, **the file is being used by another process**.

2. When I flash the SECWIM using thor2 to boot in label mode (thor2 -mode uefiflash -mmosfile "path/to/RMxxxx.secwim") and then open the program, **it opens for a few seconds showing the device information and then closes unexpectedly**.

I'm not sure if this is because I did a rebrand to my device (originally it's a Lumia 650 RM-1150 from Cricket) as I can't test on its factory firmware due to the process changing the PlatformID (from **Microsoft.MSM8909.P6237_CRICKET** to **Microsoft.MSM8909.P6237.2.0**). Can the latter influence the bootloader unlocking? Since I also have this problem but I will upload it in its own issue.

### Steps To Reproduce

**Boot to Label mode**
1. Open WPInternals.
2. In the "**Phone**" section, go to "**Manual Mode**"
3. Select "**Switch to label mode**".

Now, the program restarts the phone in Flash mode and starts downloading the test mode package (**RM-xxxx.secwim**) to flash it on the device to access the label mode.

**After booting to Label mode**
- Just open WPInternals

### Expected behavior

**Boot to Label mode**
- WPInternals should flash the file to the device and reboot it in label mode.

**After booting to Label mode**
- The program must be kept open

### WPinternals Version

v2.9.2/v3.0 Preview 1

### Windows Version

Windows 11 Pro 10.0.22631.2715

### Phone model

Lumia 650 (RM-1150)

### Relevant Assets

[WPInternals.log](https://github.com/ReneLergner/WPinternals/files/13488746/WPInternals.log)

**Comment by gus33000** [comment]
Fixed in WPinternals 3.0 preview 3
