### ISSUE TITLE
I can't click on any items

### ISSUE THREAD

**Issue by hooddy** [ReneLergner/WPinternals#61]
### Description

I current WPI 3.0  Preview 1 I can not click on any items on UI. 

### Expected behavior

Like in previous releases click to items have result.

### WPinternals Version

v3.0.8730.32231

### Windows Version

Windows 10 x64 10.0.19045.3693

**Comment by gus33000** [comment]
What kind of input device are you using? Mouse? Finger? Pen?

**Comment by gus33000** [comment]
Closing as the person has not replied within a year
