### ISSUE TITLE
Does WPinternals support HTC 8x (c620t)?

### ISSUE THREAD

**Issue by eeyrw** [ReneLergner/WPinternals#64]
### Description

I follow the getting stared installing emergency tools driver and fail to connect.

### Expected behavior

The HTC 8x gets unlocked.

### WPinternals Version

v2.9.2

### Windows Version

Windows 10 Pro 22H2 19045.3930

### Phone model

HTC 8x (c620t)

**Comment by gus33000** [comment]
Hi, wpinternals only support lumias, the tool itself should contain a list of supported models (which should only be lumias)
