### ISSUE TITLE
Lumia 950 - BootMgr.efi boot failure error screen during bootloader unlock operation

### ISSUE THREAD

**Issue by azure-hu** [ReneLergner/WPinternals#68]
### Description

I wanted to unlock bootloader of my Lumia 950 for back up the entire file system, before trying Windows on ARM. 
Although guides said a donor firmware should be selected too, there was no donor firmware selection link or button.
During bootloader unlock process, after some reboot, the device displayed blue screen with no text just the "sad smiley". 
The application displayed "Patching", but the log has many messages: "Error: The volume does not contain a recognized file system. Please make sure that all required file system drivers are loaded and that the volume is not corrupted."
Now the phone cannot be booted, only the BSOD appears.

### Expected behavior

Successful unlock of failure without corrupting OS.

### WPinternals Version

v.2.9.2

### Windows Version

Windows 10 Mobile last version

### Phone model

Lumia 950 RM-1118_15185

### Relevant Assets

[WPInternals.log](https://github.com/ReneLergner/WPinternals/files/15062540/WPInternals.log)

**Comment by gus33000** [comment]
Hi,

please retry using WPinternals 3.0 preview 3: https://github.com/ReneLergner/WPinternals/releases/tag/3.0-preview3
