### ISSUE TITLE
unlock bootloader not working (Custom flash failed)

### ISSUE THREAD

**Issue by Kopfgeldjaeger007** [ReneLergner/WPinternals#8]
My Phone: 950XL Dual black, Productcode: 059X400

Got the error: Custom flash failed

https://www.woaproject.net/download/file.php?id=76
https://www.woaproject.net/download/file.php?id=82

[WPInternals.log](https://github.com/ReneLergner/WPinternals/files/4054467/WPInternals.log)

Any idea?

**Comment by gus33000** [comment]
Are you able to reproduce with this new version? https://github.com/ReneLergner/WPinternals/releases/tag/2.9

**Comment by Kopfgeldjaeger007** [comment]
![grafik](https://user-images.githubusercontent.com/59837764/149596154-d9636b68-5abd-4a97-adc4-559b8cd007e2.png)
