### ISSUE TITLE
How to build latest commit

### ISSUE THREAD

**Issue by jack-obrien** [ReneLergner/WPinternals#84]
Hi there, it would be nice to have a few instructions on how to build the program up to the latest master commit. Thanks for your work project maintainer!

**Comment by gus33000** [comment]
Hi, 

if you desire to build it using the command line as part of automation work then you can study the ci.yaml file used for our continuous integration workflow on GitHub. 

For building it with an environment simply open the .sln using Visual Studio and build it/start it using Visual studio. No extra steps or preparation required. It's clone and play so to speak.
