### ISSUE TITLE
No Firmware Image for Lumia 950 XL

### ISSUE THREAD

**Issue by SebRock124** [ReneLergner/WPinternals#86]
### Description

The Software is refusing to show files for the Lumia 950 XL Dual Sim

### Expected behavior

I wanted it to show the firmware image files.

### WPinternals Version

2.9

### Windows Version

Windows 11 Home Build 26100

### Phone model

Lumia 950 XL (RM-1116)

### Relevant Assets

![Screenshot 2024-12-22 163844](https://github.com/user-attachments/assets/b983f4f0-7ee5-4d48-9f37-113a84c68c26)

**Comment by gus33000** [comment]
Hi, Microsoft has retired completely the server that hosted and provided the rest api to download Lumia firmware files. As a result the application is not going to help you download files anymore. You can try your best to find a public mirror of said files for your phone (check out lumiafirmware.com or archive.org and try searching for your model number and product code).

There is nothing we can do here.

**Comment by SebRock124** [comment]
Thank you. I can't believe they did that.
